### ISSUE TITLE
Manage the error log (not kill the loop)

### ISSUE THREAD

**Issue by avouspierre** [LMontalbano/Clients_Service_ITxPT#1]
When there is a issue in the NTP server, the program kills the loop : 
```
pierrelagarde@MBP-de-Pierre-2 Client_ITxPT_NTP % python3 Client_NTP_time.py
Traceback (most recent call last):
  File "Client_NTP_time.py", line 80, in <module>
    print(RequestTimefromNtp())
  File "Client_NTP_time.py", line 38, in RequestTimefromNtp
    mySocket.sendto(data, (addr, 123))
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

The program should continue to run and logs the issue in the stream.

**Comment by LMontalbano** [comment]
Issue resolved.
